### ISSUE TITLE
使用智能助理3.x的官方接口获取快递数据

### ISSUE THREAD

**Issue by sususweet** [Robotxm/BetterMiuiExpress#1]

**Comment by Robotxm** [comment]
旧版智能助理接口的可用性以及是否有调用限制等问题还暂时不清楚，我手上也没有相关的文档。如果要更换接口的话可能还得花点功夫。

**Comment by sususweet** [comment]
> 旧版智能助理接口的可用性以及是否有调用限制等问题还暂时不清楚，我手上也没有相关的文档。如果要更换接口的话可能还得花点功夫。

旧版智能助理接口的可用性可以参见“简快递”这个app，调用限制目前没发现，其数据源相对来说是比较全的

**Comment by Robotxm** [comment]
大概研究了一下旧版的数据源，返回的内容和快递 100 或者菜鸟这两个接口不太一样，如果要换接口的话需要做比较多的事情。这个放在以后再看吧，暂时先不换数据源了。

**Comment by Robotxm** [comment]
已经支持菜鸟裹裹和快递 100 两个数据接口，不再考虑使用旧版智能助理接口。
