### ISSUE TITLE
点击进入物流详情两次，第三次就会出现“暂无运单信息”

### ISSUE THREAD

**Issue by jeffreyleeeee** [Robotxm/BetterMiuiExpress#10]
![Screenshot_2023-03-14-09-44-08-983_com moefactory bettermiuiexpress](https://user-images.githubusercontent.com/127806066/224870810-4d5b6b33-78ba-4506-ad9d-cb614b831989.jpg)
所有快递都是这样，希望大大修复

**Comment by jeffreyleeeee** [comment]
智能助理版本5.5.64，上述情况必然复现

**Comment by Robotxm** [comment]
菜鸟有调用频次限制，而且非常激进，暂时没办法解决

**Comment by yaowans** [comment]
用的快递100接口 1.4.5版本也出现上述错误。
