### ISSUE TITLE
顺丰快递数据不显示

### ISSUE THREAD

**Issue by wuchjun** [Robotxm/BetterMiuiExpress#7]
菜鸟裹裹应该没有顺丰快递数据，MIUI快递助手官方支持顺丰快递数据查询，应该要过滤一下调用![Screenshot_2023-01-14-09-45-16-860_com.moefactory.bettermiuiexpress.jpg](https://user-images.githubusercontent.com/1947712/212445019-20d823a5-acb0-4a7a-a259-9fd7916bf611.jpg)

**Comment by xuanmi666** [comment]
还有京东也会跳菜鸟裹裹无数据

**Comment by wuchjun** [comment]
> 还有京东也会跳菜鸟裹裹无数据

我的京东快递好像正常

**Comment by Robotxm** [comment]
你这个界面不是模块的界面吧，右上角都没有菜单

**Comment by wuchjun** [comment]
> 你这个界面不是模块的界面吧，右上角都没有菜单

这个不清楚，但是确实是使用模块后顺丰才没数据的，取消模块后就有

**Comment by Robotxm** [comment]
> > 你这个界面不是模块的界面吧，右上角都没有菜单
> 
> 这个不清楚，但是确实是使用模块后顺丰才没数据的，取消模块后就有

取消模块之后顺丰的详情页跳转是什么样的，能把隐私信息打码然后截个图吗

**Comment by wuchjun** [comment]
> > > 你这个界面不是模块的界面吧，右上角都没有菜单
> > 
> > 这个不清楚，但是确实是使用模块后顺丰才没数据的，取消模块后就有
> 
> 取消模块之后顺丰的详情页跳转是什么样的，能把隐私信息打码然后截个图吗

![Screenshot_2023-01-18-20-38-06-688_com.miui.personalassistant-edit.jpg](https://user-images.githubusercontent.com/1947712/213206915-db8afc47-be78-4710-bb69-48949fb7d693.jpg)

**Comment by Robotxm** [comment]
> > > > 你这个界面不是模块的界面吧，右上角都没有菜单
> > > 
> > > 
> > > 这个不清楚，但是确实是使用模块后顺丰才没数据的，取消模块后就有
> > 
> > 
> > 取消模块之后顺丰的详情页跳转是什么样的，能把隐私信息打码然后截个图吗
> 
> ![Screenshot_2023-01-18-20-38-06-688_com.miui.personalassistant-edit.jpg](https://user-images.githubusercontent.com/1947712/213206915-db8afc47-be78-4710-bb69-48949fb7d693.jpg)

那看起来官方在新版已经支持了，回头我过滤一下版本号吧

**Comment by ghcsd** [comment]
确实有同样的问题

**Comment by Robotxm** [comment]
1.4.4 不再拦截顺丰快递。需要同时配合最新版本的智能助理使用。
