### ISSUE TITLE
显示暂无运单信息

### ISSUE THREAD

**Issue by ZYong9908** [Robotxm/BetterMiuiExpress#8]
![Screenshot_2023-02-13-17-45-01-880_com miui personalassistant-edit](https://user-images.githubusercontent.com/44081531/218424820-2129f014-fbdc-4337-8424-b893a75b30a3.jpg)
![Screenshot_2023-02-13-17-44-53-946_com moefactory bettermiuiexpress](https://user-images.githubusercontent.com/44081531/218425624-d59a9348-aae2-40ad-9d5b-dd5e772272fe.jpg)

无论使用菜鸟源还是自己申请的快递100key都这样
版本1.4.4
智能助理5.5.60

**Comment by ZYong9908** [comment]
![Uploading Screenshot_2023-02-13-17-44-53-946_com.moefactory.bettermiuiexpress.jpg…]()

**Comment by yaowans** [comment]
一样的错误，期待修复，MIUI14，版本1.4.5 智能助理5.5.64

**Comment by brainhole39** [comment]
也是一样的错误 打开模块之后的第一次能正常查询 后面的就不行了 可能是阿里那边又改了什么东西

**Comment by brainhole39** [comment]
> 

版本1.4.5
智能助理5.5.76

**Comment by Robotxm** [comment]
已经发布 1.5.0，增加了一个新的快递 100 数据源，可以再试一试。

另外，建议卸载旧版之后再升级 1.5.0。
